// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetImageCd/GetImageCd.proto

package go_micro_srv_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	// 错误码
	Errno string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	// 错误消息
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	// 图片结构信息
	Pix []byte `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	// 图片跨步
	Stride int64 `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	// min max Point
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{3}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{4}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_208a871f55559f63, []int{6}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.GetImageCd.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.GetImageCd.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.GetImageCd.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.GetImageCd.Pong")
}

func init() { proto.RegisterFile("proto/GetImageCd/GetImageCd.proto", fileDescriptor_208a871f55559f63) }

var fileDescriptor_208a871f55559f63 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xda, 0x30,
	0x18, 0xc5, 0x24, 0x01, 0xf6, 0x8d, 0x03, 0xb3, 0xd0, 0x16, 0x65, 0x62, 0x0a, 0xd9, 0x61, 0x61,
	0x87, 0x0c, 0xb1, 0xd3, 0xce, 0x08, 0x4d, 0x3b, 0x30, 0x21, 0xa3, 0x4a, 0x70, 0x74, 0xc1, 0x8a,
	0xac, 0x12, 0x9b, 0xda, 0xa6, 0xa2, 0xff, 0xa2, 0x7f, 0xb8, 0x52, 0x65, 0x13, 0x04, 0xaa, 0x1a,
	0xda, 0xde, 0xde, 0xcb, 0x7b, 0x4f, 0xf6, 0x7b, 0x91, 0xa1, 0xbf, 0x55, 0xd2, 0xc8, 0x5f, 0x7f,
	0x99, 0xf9, 0x57, 0xd0, 0x9c, 0x8d, 0xd7, 0x67, 0x30, 0x73, 0x1a, 0xfe, 0x92, 0xcb, 0xac, 0xe0,
	0x2b, 0x25, 0x33, 0xad, 0xee, 0xb2, 0x93, 0x9c, 0x7c, 0x85, 0xe6, 0x94, 0x69, 0x4d, 0x73, 0x86,
	0x3b, 0xe0, 0x69, 0x7a, 0x1f, 0xa2, 0x18, 0xa5, 0x1f, 0x88, 0x85, 0x49, 0x0f, 0x9a, 0x84, 0xdd,
	0xee, 0x98, 0x36, 0x18, 0x83, 0x7f, 0xb5, 0xe3, 0xeb, 0x52, 0x75, 0x38, 0x79, 0x44, 0xd0, 0x22,
	0x4c, 0x6f, 0xa5, 0xd0, 0x0c, 0x77, 0x21, 0x98, 0x28, 0x25, 0x64, 0xe9, 0x38, 0x10, 0xfc, 0x19,
	0x1a, 0x13, 0xa5, 0x0a, 0x9d, 0x87, 0x75, 0xf7, 0xb9, 0x64, 0xf6, 0xac, 0x19, 0xdf, 0x87, 0x5e,
	0x8c, 0xd2, 0x36, 0xb1, 0xd0, 0x3a, 0xe7, 0x46, 0xf1, 0x35, 0x0b, 0xfd, 0x18, 0xa5, 0x1e, 0x29,
	0x19, 0xfe, 0x03, 0xde, 0x94, 0x8b, 0x30, 0x88, 0x51, 0xfa, 0x71, 0xf4, 0x23, 0xab, 0xe8, 0x91,
	0x1d, 0xef, 0x91, 0xcd, 0x24, 0x17, 0x86, 0xd8, 0x8c, 0x8b, 0xd2, 0x7d, 0xd8, 0x78, 0x6f, 0x94,
	0xee, 0xa3, 0xef, 0x10, 0x38, 0x86, 0xdb, 0x80, 0x16, 0xae, 0x92, 0x47, 0xd0, 0xc2, 0xb2, 0xa5,
	0x6b, 0xe2, 0x11, 0xb4, 0x4c, 0x52, 0xe8, 0xcc, 0x8d, 0x62, 0xb4, 0xe0, 0x22, 0x3f, 0xee, 0xd4,
	0x85, 0x60, 0x25, 0x77, 0xc2, 0x94, 0x99, 0x03, 0x49, 0x06, 0xf0, 0xe9, 0xcc, 0x79, 0x5a, 0xec,
	0x05, 0xeb, 0x37, 0xf0, 0x67, 0x5c, 0xe4, 0x76, 0x0f, 0x6d, 0x94, 0xbc, 0x61, 0xa5, 0x5c, 0x32,
	0xa7, 0xcb, 0x6a, 0x7d, 0xf4, 0x50, 0x07, 0x38, 0x95, 0xc3, 0x53, 0xf0, 0xc7, 0x74, 0xb3, 0xc1,
	0xf1, 0x85, 0xfa, 0xee, 0xe6, 0x51, 0xff, 0xd5, 0x81, 0x92, 0x1a, 0x5e, 0xb9, 0xbf, 0xc4, 0x68,
	0x81, 0x07, 0x95, 0xf6, 0xe7, 0x9b, 0x44, 0x3f, 0xdf, 0x62, 0x3d, 0x1e, 0x31, 0x44, 0xf8, 0x3f,
	0xb4, 0xec, 0x04, 0xae, 0x66, 0xaf, 0x32, 0x6b, 0x2d, 0xd1, 0x05, 0x59, 0x8a, 0x3c, 0xa9, 0xa5,
	0x68, 0x88, 0xae, 0x1b, 0xee, 0x0d, 0xfc, 0x7e, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x22, 0xbd, 0x41,
	0x04, 0x28, 0x03, 0x00, 0x00,
}
