// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/PostRet/PostRet.proto

package go_micro_srv_PostRet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostRet service

type PostRetService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostRet_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (PostRet_PingPongService, error)
}

type postRetService struct {
	c    client.Client
	name string
}

func NewPostRetService(name string, c client.Client) PostRetService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostRet"
	}
	return &postRetService{
		c:    c,
		name: name,
	}
}

func (c *postRetService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostRet.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postRetService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (PostRet_StreamService, error) {
	req := c.c.NewRequest(c.name, "PostRet.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postRetServiceStream{stream}, nil
}

type PostRet_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postRetServiceStream struct {
	stream client.Stream
}

func (x *postRetServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postRetServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postRetService) PingPong(ctx context.Context, opts ...client.CallOption) (PostRet_PingPongService, error) {
	req := c.c.NewRequest(c.name, "PostRet.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postRetServicePingPong{stream}, nil
}

type PostRet_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postRetServicePingPong struct {
	stream client.Stream
}

func (x *postRetServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postRetServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postRetServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PostRet service

type PostRetHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, PostRet_StreamStream) error
	PingPong(context.Context, PostRet_PingPongStream) error
}

func RegisterPostRetHandler(s server.Server, hdlr PostRetHandler, opts ...server.HandlerOption) error {
	type postRet interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type PostRet struct {
		postRet
	}
	h := &postRetHandler{hdlr}
	return s.Handle(s.NewHandler(&PostRet{h}, opts...))
}

type postRetHandler struct {
	PostRetHandler
}

func (h *postRetHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.PostRetHandler.Call(ctx, in, out)
}

func (h *postRetHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostRetHandler.Stream(ctx, m, &postRetStreamStream{stream})
}

type PostRet_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postRetStreamStream struct {
	stream server.Stream
}

func (x *postRetStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postRetStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postRetHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostRetHandler.PingPong(ctx, &postRetPingPongStream{stream})
}

type PostRet_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postRetPingPongStream struct {
	stream server.Stream
}

func (x *postRetPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postRetPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postRetPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
